import { NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Product from '@/models/Product';

const mockDetails: Record<string, any> = {
  'steel-i-beams': { id: '1', name: 'Steel I-Beams', image: '/assets/images/steel-beam.png', description: 'High-strength structural steel I-beams perfect for construction projects.', price: 'From ₹45/kg', specifications: [{ label: 'Grade', value: 'IS 2062, IS 800' }, { label: 'Size Range', value: '100mm - 600mm' }, { label: 'Length', value: 'Up to 12 meters' }, { label: 'Tensile Strength', value: '410-540 N/mm²' }], features: ['High tensile strength and durability', 'Excellent corrosion resistance', 'Easy to weld and fabricate'], applications: ['Building construction', 'Bridge construction', 'Industrial warehouses'], category: 'Structural Steel', slug: 'steel-i-beams', metadata: { title: 'Steel I-Beams | Vighnaharta Steel', description: 'Premium quality steel I-beams for construction.' } },
  'steel-rods': { id: '2', name: 'Steel Rods (TMT Bars)', image: '/assets/images/steel-rod.png', description: 'Premium quality TMT steel rods for reinforcement in concrete structures.', price: 'From ₹52/kg', specifications: [{ label: 'Grade', value: 'Fe 500D, Fe 550D' }, { label: 'Diameter', value: '8mm - 32mm' }, { label: 'Length', value: '12 meters' }, { label: 'Tensile Strength', value: '500-600 N/mm²' }], features: ['Superior strength and ductility', 'Excellent bendability', 'Earthquake resistant'], applications: ['Reinforced concrete', 'High-rise buildings', 'Bridges'], category: 'Reinforcement Steel', slug: 'steel-rods', metadata: { title: 'TMT Steel Rods | Vighnaharta Steel', description: 'High-quality TMT bars for concrete reinforcement.' } },
  'steel-sheets': { id: '3', name: 'Steel Sheets', image: '/assets/images/steel-sheet.png', description: 'High-quality steel sheets for roofing and industrial applications.', price: 'From ₹65/kg', specifications: [{ label: 'Thickness', value: '0.5mm - 6mm' }, { label: 'Width', value: 'Up to 1500mm' }, { label: 'Coating', value: 'Galvanized/CR/HR' }, { label: 'Grade', value: 'IS 277, IS 513' }], features: ['Excellent corrosion resistance', 'Lightweight yet strong', 'Weather resistant'], applications: ['Roofing and cladding', 'Industrial sheds', 'Automotive'], category: 'Sheet & Plates', slug: 'steel-sheets', metadata: { title: 'Steel Sheets | Vighnaharta Steel', description: 'Quality steel sheets for roofing.' } },
  'steel-pipes': { id: '4', name: 'Steel Pipes', image: '/assets/images/steel-pipe.png', description: 'Seamless and welded steel pipes for water supply and structural applications.', price: 'From ₹58/kg', specifications: [{ label: 'Size Range', value: '15mm - 600mm' }, { label: 'Grade', value: 'IS 1239, IS 3589' }, { label: 'Type', value: 'ERW, Seamless' }, { label: 'Pressure Rating', value: 'Up to 40 kg/cm²' }], features: ['High pressure resistance', 'Smooth internal surface', 'Long service life'], applications: ['Water supply', 'Gas distribution', 'Industrial piping'], category: 'Tubular Products', slug: 'steel-pipes', metadata: { title: 'Steel Pipes | Vighnaharta Steel', description: 'Quality pipes for plumbing and industrial use.' } },
  'steel-angles': { id: '5', name: 'Steel Angles', image: '/assets/images/steel-beam.png', description: 'L-shaped steel angles for construction and fabrication work.', price: 'From ₹48/kg', specifications: [{ label: 'Size Range', value: '20x20mm to 200x200mm' }, { label: 'Thickness', value: '3mm - 20mm' }, { label: 'Grade', value: 'IS 2062' }], features: ['High structural strength', 'Precise dimensions', 'Easy to weld'], applications: ['Structural framework', 'Tower fabrication', 'Industrial shelving'], category: 'Structural Steel', slug: 'steel-angles', metadata: { title: 'Steel Angles | Vighnaharta Steel', description: 'L-shaped steel angles for construction.' } },
  'steel-channels': { id: '6', name: 'Steel Channels', image: '/assets/images/steel-beam.png', description: 'C-shaped steel channels for structural applications and frameworks.', price: 'From ₹50/kg', specifications: [{ label: 'Size Range', value: '75mm - 400mm' }, { label: 'Grade', value: 'IS 808' }, { label: 'Length', value: '12m standard' }], features: ['High load-bearing capacity', 'Uniform dimensions', 'Excellent weldability'], applications: ['Building framework', 'Vehicle chassis', 'Platform supports'], category: 'Structural Steel', slug: 'steel-channels', metadata: { title: 'Steel Channels | Vighnaharta Steel', description: 'C-shaped channels for structural use.' } },
  'steel-plates': { id: '7', name: 'Steel Plates', image: '/assets/images/steel-sheet.png', description: 'Heavy-duty steel plates for industrial machinery and heavy construction.', price: 'From ₹55/kg', specifications: [{ label: 'Thickness', value: '6mm - 100mm' }, { label: 'Grade', value: 'IS 2062, IS 2025' }, { label: 'Surface', value: 'Hot Rolled, Shot Blasted' }], features: ['High tensile strength', 'Excellent impact resistance', 'Wide thickness range'], applications: ['Pressure vessels', 'Shipbuilding', 'Heavy machinery'], category: 'Sheet & Plates', slug: 'steel-plates', metadata: { title: 'Steel Plates | Vighnaharta Steel', description: 'Heavy-duty plates for industrial use.' } },
  'steel-wire': { id: '8', name: 'Steel Wire', image: '/assets/images/steel-rod.png', description: 'High-tensile steel wire for binding, fencing, and reinforcement work.', price: 'From ₹60/kg', specifications: [{ label: 'Diameter', value: '0.5mm - 12mm' }, { label: 'Tensile Strength', value: '300-1800 N/mm²' }, { label: 'Coating', value: 'Galvanized, Black' }], features: ['High tensile strength', 'Excellent flexibility', 'Corrosion resistant options'], applications: ['Binding wire', 'Fencing', 'Reinforcement'], category: 'Reinforcement Steel', slug: 'steel-wire', metadata: { title: 'Steel Wire | Vighnaharta Steel', description: 'High-tensile wire for binding and fencing.' } },
};

export async function GET(_request: Request, { params }: { params: Promise<{ slug: string }> }) {
  try {
    const { slug } = await params;

    await connectDB();
    const dbProduct = await Product.findOne({ slug }).lean() as any;

    if (dbProduct) {
      return NextResponse.json({ success: true, data: { ...dbProduct, id: dbProduct._id.toString() } });
    }

    const mock = mockDetails[slug];
    if (!mock) return NextResponse.json({ success: false, error: 'Product not found' }, { status: 404 });
    return NextResponse.json({ success: true, data: mock });
  } catch {
    return NextResponse.json({ success: false, error: 'Failed to fetch product' }, { status: 500 });
  }
}
